spring:
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: com.example.mappingpersistence.config.CENamingStrategy
    database-platform: org.hibernate.dialect.PostgreSQLDialect